"""Reporter agent — produces the post-incident report as Markdown."""
from __future__ import annotations

from pathlib import Path

from ..models import ActionStatus, Incident
from .base import BaseAgent

REPORT_SYSTEM = """Write a crisp executive summary (3-6 sentences) of a security incident for a CISO.
State what happened, how it was detected, what the agents did autonomously, what needed a human, and residual risk. No headings."""


class ReporterAgent(BaseAgent):
    name = "reporter"

    def write(self, inc: Incident, out_dir: Path) -> Path:
        out_dir.mkdir(parents=True, exist_ok=True)
        summary = self.brain.narrate("executive_summary", inc.model_dump(mode="json", exclude={"communications"}), system=REPORT_SYSTEM)
        t, inv = inc.triage, inc.investigation
        lines = [f"# Incident report — {inc.id}", "",
                 f"**Alert:** {inc.alert.id} · {inc.alert.rule} · {inc.alert.timestamp:%Y-%m-%d %H:%M UTC}  ",
                 f"**Title:** {inc.alert.title}  ",
                 f"**Final state:** `{inc.state.value}` · **Ticket:** {inc.ticket_id or '-'} · **Reasoning back-end:** {inc.brain}", "",
                 "## Executive summary", "", summary, ""]
        if t:
            lines += ["## Triage", "", f"| Field | Value |", "|---|---|",
                      f"| Verdict | {t.verdict.value} |", f"| Severity | {t.severity.value} |",
                      f"| Confidence | {t.confidence} |", f"| Category / playbook | {t.category} |",
                      f"| MITRE ATT&CK | {', '.join(t.mitre_techniques) or '-'} |", "",
                      f"**Rationale:** {t.rationale}", ""]
            fired = [k for k, v in t.signals.items() if v and not k.startswith("allowlist_") and k not in ("asset_criticality", "asset_environment", "ti_malicious", "ti_suspicious")]
            if fired:
                lines += ["**Signals:** " + ", ".join(f"`{k}`" for k in fired), ""]
        if inv:
            lines += ["## Investigation", "", f"**Root cause:** {inv.root_cause}  ", f"**Data at risk:** {inv.data_at_risk}  ",
                      f"**Lateral movement:** {'yes' if inv.lateral_movement else 'no'} · **Confidence:** {inv.confidence}", "",
                      f"**Affected hosts:** {', '.join(inv.affected_hosts) or '-'}  ", f"**Affected users:** {', '.join(inv.affected_users) or '-'}", "",
                      "### Findings", ""] + [f"- {f}" for f in inv.findings] + [""]
            iocs = [f"`{v}` ({k})" for k, vs in inv.iocs.items() for v in vs]
            if iocs:
                lines += ["### Indicators of compromise", ""] + [f"- {i}" for i in iocs] + [""]
            if inv.timeline:
                lines += ["### Timeline", "", "| Time (UTC) | Source | Event |", "|---|---|---|"]
                lines += [f"| {e.timestamp:%H:%M:%S} | {e.source} | {e.description.replace('|', '/')} |" for e in inv.timeline]
                lines.append("")
        if inc.actions:
            lines += ["## Response actions", "", "| Action | Tier | Gate | Status | Verified | Decision |", "|---|---|---|---|---|---|"]
            for a in inc.actions:
                gate = "human" if a.requires_approval else "auto"
                who = ""
                if a.approval and a.approval.approved is not None:
                    who = f"{'approved' if a.approval.approved else 'denied'} by {a.approval.approver}" + (f" — {a.approval.comment}" if a.approval.comment else "")
                elif a.status == ActionStatus.SKIPPED:
                    who = (a.result or {}).get("skipped_reason", "")
                ver = {True: "✅", False: "❌", None: "–"}[a.verified]
                lines.append(f"| `{a.describe()}` | {a.risk_tier.value} | {gate} | {a.status.value} | {ver} | {who} |")
            lines.append("")
        if inc.communications:
            lines += ["## Communications", ""] + [f"- **{c.channel}** → {c.recipient}: {c.subject}" for c in inc.communications] + [""]
        lines += ["## State history", "", "| Time | From | To | Actor | Note |", "|---|---|---|---|---|"]
        lines += [f"| {h.at:%H:%M:%S} | {h.from_state.value} | {h.to_state.value} | {h.actor} | {h.note} |" for h in inc.history]
        lines += ["", "## Notes", ""] + [f"- {n}" for n in inc.notes] + ["",
                  "_Generated by SOC Autopilot. Every tool call and decision is in the hash-chained audit log (`out/audit.jsonl`)._", ""]
        path = out_dir / f"{inc.id}.md"
        path.write_text("\n".join(lines), encoding="utf-8")
        inc.report_path = str(path)
        self.log(inc, "report_written", path=str(path))
        return path
